export const theme = {
  colors: {
    primary: '#2DA5FE',
    mainBlue: '#2C8BFD',
    text: 'white',
    bodyText: '#787381',
    background: '#F5F9FC',
    secondaryBackground: 'white',
    darkGray: '#787381',
    titleText: '#190044',
    darkDivider: '#EDECEE',
    darkBlue: '#190044',
    mediumRed: '#F56565',
    whiteText: 'white',
    mainBg: '#F5F9FC',
    veryLightGray: '#EDECEE',
  },
  font: {
    black: 'Inter-Black',
    bold: 'Inter-Bold',
    extraBold: 'Inter-ExtraBold',
    extraLight: 'Inter-ExtraLight',
    light: 'Inter-Light',
    medium: 'Inter-Medium',
    regular: 'Inter-Regular',
    semiBold: 'Inter-SemiBold',
    thin: 'Inter-Thin',
  },
};
